### PR TITLE
Fixes issue #35

### PR DESCRIPTION
**Pull request by JPFrancoia**

### CODE REVIEW

**Comment by adaniello** [comment]
Only two considerations:
1. i think that you missed to pass $afterWhere as argument in executeSelect; eg

stmt = $this->executeSelect($tableName, $column, $where, $afterWhere);

2. in every case, i think that this is useless; with $afterWhere i should pass "after where" arguments to query (eg. "order" and/or "limit"), but with selectValue i get only one column of one record and usually we do it with only "where" condition.

It's my opinion.

**Comment by JPFrancoia** [comment]
I corrected my PR. But it was useless:

I realized I'm using the release 3.1.5 of atomik (I'm using Atomik in production). As described in #35, there is really a bug in this release. The code has changed in the master branch.

There is no more afterWhere parameter in the function selectValue.

What shall we do with this PR ?

**Comment by adaniello** [comment]
What shall we do with this PR? I don't know.
Maybe close it
;P

**Comment by JPFrancoia** [comment]
Knew it :) Just in case.

**Pull request closed without merging**
